import type { ModuleManifest } from "@/features/modules/types"
import { reviewChrome, BOOKS_SECTIONS } from "@/features/modules/manifests/reviewSections"

export const booksManifest: ModuleManifest = {
  id: "books",
  name: "Books",
  shortName: "Books",
  tagline: "Premium reading notes",
  parserType: "book",
  destinationModule: "books",
  ready: false,
  route: "/books",
  identity: { icon: "BookOpen", mood: "reading" },
  theme: {
    mode: "dark",
    tokens: {
      bg: "transparent",
      fg: "hsl(40 10% 96%)",
      muted: "hsl(270 8% 62%)",
      card: "rgba(14, 12, 22, 0.88)",
      border: "rgba(168, 85, 247, 0.22)",
      accent: "#a855f7",
      accentSoft: "rgba(168, 85, 247, 0.14)",
      positive: "#4d7c57",
      negative: "#b54a3c",
      warning: "#b45309",
      paper: "rgba(18, 14, 28, 0.9)",
      glow: "rgba(168, 85, 247, 0.16)",
      progress: "rgba(168, 85, 247, 0.75)",
      radius: "1.25rem",
    },
    fontDisplay: '"Fraunces", ui-serif, Georgia, serif',
  },
  import: {
    upload: {
      eyebrow: "Books · Import",
      title: "Reading Notebook",
      description: "Capture book name, author, chapter, and handwritten notes from your pages.",
      dropTitle: "Drop reading notebook pages",
      dropHint: "Chapter notes · highlights · vocabulary",
      sessionLabel: "Book / session title",
      sessionPlaceholder: "e.g. Atomic Habits — Ch. 3",
      addImagesLabel: "Add pages",
      changeImagesLabel: "Change pages",
      processLabel: "Process notes",
      reprocessLabel: "Re-process notes",
    },
    understand: {
      title: "Book notes?",
      description: "Confirm Books for a reading-focused review: summary, quotes, vocabulary.",
    },
    review: reviewChrome({
      title: "Review Book Notes",
      description: "Review AI-extracted sections, then save.",
      imagesHeading: "Original Notebook",
      saveLabel: "Save Book Notes",
      successTitle: "Successfully Saved!",
      successCta: "View in Books",
      successRoute: "/books",
    }),
    motion: ["paper-turn", "fade-rise"],
  },
  review: {
    layout: "book-folio",
    hero: "cover",
    showConfidence: true,
    sections: BOOKS_SECTIONS,
    fieldGroups: [
      { id: "header", label: "Book information", icon: "BookOpen", order: 0 },
      { id: "body", label: "Chapter notes", icon: "NotebookPen", order: 1 },
      { id: "planned", label: "Planned fields", icon: "Sparkles", order: 2 },
      { id: "main", label: "Summary", order: 3 },
    ],
  },
  surfaces: {
    headerStyle: "folio",
    navStyle: "editorial",
    dashboardWidgets: ["library", "vocab", "open-import"],
  },
}
