import type { ModuleManifest } from "@/features/modules/types"
import { reviewChrome, FINANCE_SECTIONS } from "@/features/modules/manifests/reviewSections"

export const financeManifest: ModuleManifest = {
  id: "finance",
  name: "Finance",
  shortName: "Finance",
  tagline: "Research and money notes",
  parserType: "finance",
  destinationModule: "finance",
  ready: false,
  route: "/finance",
  identity: { icon: "Wallet", mood: "ledger" },
  theme: {
    mode: "dark",
    tokens: {
      bg: "transparent",
      fg: "hsl(160 10% 96%)",
      muted: "hsl(170 8% 58%)",
      card: "rgba(10, 16, 16, 0.72)",
      border: "rgba(45, 212, 191, 0.14)",
      accent: "#3b82f6",
      accentSoft: "rgba(45, 212, 191, 0.12)",
      positive: "hsl(152 55% 42%)",
      negative: "hsl(0 70% 55%)",
      warning: "hsl(38 90% 55%)",
      paper: "rgba(8, 14, 14, 0.55)",
      glow: "rgba(45, 212, 191, 0.12)",
      progress: "rgba(45, 212, 191, 0.7)",
      radius: "1.2rem",
    },
    fontMono: "ui-monospace, SFMono-Regular, Menlo, monospace",
  },
  import: {
    upload: {
      eyebrow: "Finance · Import",
      title: "Finance Notebook",
      description: "Investment research, expense notes, and watchlist ideas from your pages.",
      dropTitle: "Drop finance notebook pages",
      dropHint: "Research · expenses · thesis notes",
      sessionLabel: "Notebook title",
      sessionPlaceholder: "e.g. Q3 watchlist research",
      addImagesLabel: "Add pages",
      changeImagesLabel: "Change pages",
      processLabel: "Process notes",
      reprocessLabel: "Re-process notes",
    },
    understand: {
      title: "Finance notes?",
      description: "Confirm Finance for thesis, risk, and action items.",
    },
    review: reviewChrome({
      title: "Review Finance",
      description: "Review AI-extracted sections, then save.",
      imagesHeading: "Original Notebook",
      saveLabel: "Save Finance Notes",
      successTitle: "Successfully Saved!",
      successCta: "View in Finance",
      successRoute: "/finance",
    }),
    motion: ["fade-rise"],
  },
  review: {
    layout: "ledger-split",
    hero: "notebook",
    showConfidence: true,
    sections: FINANCE_SECTIONS,
    fieldGroups: [
      { id: "header", label: "Basics", order: 0 },
      { id: "body", label: "Thesis & notes", order: 1 },
      { id: "planned", label: "Risk & actions", order: 2 },
    ],
  },
  surfaces: {
    headerStyle: "minimal",
    navStyle: "dense",
    dashboardWidgets: ["open-import"],
  },
}
