import type { ReviewChrome, ReviewSectionDef } from "@/features/modules/types"

export function reviewChrome(
  partial: Partial<ReviewChrome> & Pick<ReviewChrome, "title" | "description">,
): ReviewChrome {
  return {
    draftHeading: "Draft",
    imagesHeading: "Original Pages",
    saveLabel: "Save",
    successTitle: "Successfully Saved!",
    successCta: "View module",
    successRoute: "/",
    ...partial,
  }
}

/** Sections match the shared design mockup exactly. */
export const TRADING_SECTIONS: ReviewSectionDef[] = [
  {
    id: "market_context",
    label: "Market Context",
    icon: "LineChart",
    matchKeys: ["market", "context", "bias", "uncategorized"],
    kind: "content",
    order: 0,
  },
  {
    id: "setup",
    label: "Trade Setup",
    icon: "Target",
    matchKeys: ["setup", "plan"],
    kind: "content",
    order: 1,
  },
  {
    id: "execution",
    label: "Execution",
    icon: "Zap",
    matchKeys: ["execution", "entry", "exit"],
    kind: "content",
    order: 2,
  },
  {
    id: "psychology",
    label: "Psychology",
    icon: "Brain",
    matchKeys: ["psych", "emotion", "mindset"],
    kind: "content",
    order: 3,
  },
  {
    id: "lessons",
    label: "Lessons",
    icon: "Lightbulb",
    matchKeys: ["lesson", "learning"],
    kind: "content",
    order: 4,
  },
  { id: "trades", label: "Trades", icon: "CandlestickChart", matchKeys: [], kind: "trades", order: 5 },
  { id: "session", label: "Session", icon: "Calendar", matchKeys: [], kind: "session", order: 6 },
]

export const BOOKS_SECTIONS: ReviewSectionDef[] = [
  { id: "session", label: "Book Info", icon: "BookOpen", matchKeys: [], kind: "session", order: 0 },
  {
    id: "summary",
    label: "Summary",
    icon: "AlignLeft",
    matchKeys: ["summary", "overview"],
    kind: "content",
    order: 1,
  },
  {
    id: "chapter",
    label: "Chapter Notes",
    icon: "NotebookPen",
    matchKeys: ["chapter", "notes", "uncategorized"],
    kind: "content",
    order: 2,
  },
  {
    id: "learnings",
    label: "Key Learnings",
    icon: "Sparkles",
    matchKeys: ["learning", "key"],
    kind: "content",
    order: 3,
  },
  {
    id: "quotes",
    label: "Quotes",
    icon: "Quote",
    matchKeys: ["quote"],
    kind: "content",
    order: 4,
  },
  {
    id: "vocab",
    label: "Vocabulary",
    icon: "BookA",
    matchKeys: ["vocab", "word"],
    kind: "content",
    order: 5,
  },
  {
    id: "reflection",
    label: "Reflection",
    icon: "Heart",
    matchKeys: ["reflect"],
    kind: "content",
    order: 6,
  },
  {
    id: "actions",
    label: "Action Items",
    icon: "CheckSquare",
    matchKeys: ["action"],
    kind: "content",
    order: 7,
  },
]

export const FINANCE_SECTIONS: ReviewSectionDef[] = [
  { id: "session", label: "Overview", icon: "Wallet", matchKeys: [], kind: "session", order: 0 },
  {
    id: "thesis",
    label: "Investment Thesis",
    icon: "FileText",
    matchKeys: ["thesis", "summary"],
    kind: "content",
    order: 1,
  },
  {
    id: "research",
    label: "Research",
    icon: "Search",
    matchKeys: ["research", "uncategorized"],
    kind: "content",
    order: 2,
  },
  {
    id: "risk",
    label: "Risk",
    icon: "ShieldAlert",
    matchKeys: ["risk"],
    kind: "content",
    order: 3,
  },
  {
    id: "watchlist",
    label: "Watchlist",
    icon: "List",
    matchKeys: ["watch"],
    kind: "content",
    order: 4,
  },
  {
    id: "actions",
    label: "Action Items",
    icon: "CheckSquare",
    matchKeys: ["action"],
    kind: "content",
    order: 5,
  },
]

export const CAREER_SECTIONS: ReviewSectionDef[] = [
  { id: "session", label: "Meeting Info", icon: "Briefcase", matchKeys: [], kind: "session", order: 0 },
  {
    id: "discussion",
    label: "Discussion",
    icon: "MessagesSquare",
    matchKeys: ["discussion", "notes"],
    kind: "content",
    order: 1,
  },
  {
    id: "decisions",
    label: "Decisions",
    icon: "GitBranch",
    matchKeys: ["decision"],
    kind: "content",
    order: 2,
  },
  {
    id: "tasks",
    label: "Tasks",
    icon: "ListTodo",
    matchKeys: ["task"],
    kind: "content",
    order: 3,
  },
  {
    id: "followups",
    label: "Follow Ups",
    icon: "CornerUpRight",
    matchKeys: ["follow", "action"],
    kind: "content",
    order: 4,
  },
  {
    id: "project",
    label: "Project",
    icon: "FolderKanban",
    matchKeys: ["project", "uncategorized"],
    kind: "content",
    order: 5,
  },
]

export const HEALTH_SECTIONS: ReviewSectionDef[] = [
  {
    id: "workout",
    label: "Workout",
    icon: "Dumbbell",
    matchKeys: ["workout", "training", "uncategorized"],
    kind: "content",
    order: 0,
  },
  {
    id: "nutrition",
    label: "Nutrition",
    icon: "Apple",
    matchKeys: ["nutrition", "diet", "food"],
    kind: "content",
    order: 1,
  },
  {
    id: "measurements",
    label: "Measurements",
    icon: "Ruler",
    matchKeys: ["measure", "weight"],
    kind: "content",
    order: 2,
  },
  {
    id: "progress",
    label: "Progress",
    icon: "Activity",
    matchKeys: ["progress"],
    kind: "content",
    order: 3,
  },
  {
    id: "notes",
    label: "Notes",
    icon: "Notebook",
    matchKeys: ["note", "health"],
    kind: "content",
    order: 4,
  },
  { id: "session", label: "Session", icon: "HeartPulse", matchKeys: [], kind: "session", order: 5 },
]

export const KNOWLEDGE_SECTIONS: ReviewSectionDef[] = [
  { id: "session", label: "Title", icon: "StickyNote", matchKeys: [], kind: "session", order: 0 },
  {
    id: "summary",
    label: "Summary",
    icon: "AlignLeft",
    matchKeys: ["summary", "uncategorized"],
    kind: "content",
    order: 1,
  },
  {
    id: "concepts",
    label: "Key Concepts",
    icon: "Hexagon",
    matchKeys: ["concept", "key"],
    kind: "content",
    order: 2,
  },
  {
    id: "references",
    label: "References",
    icon: "Link",
    matchKeys: ["reference", "source"],
    kind: "content",
    order: 3,
  },
  {
    id: "related",
    label: "Related Topics",
    icon: "Share2",
    matchKeys: ["related", "topic"],
    kind: "content",
    order: 4,
  },
  {
    id: "notes",
    label: "Personal Notes",
    icon: "PenLine",
    matchKeys: ["note", "personal"],
    kind: "content",
    order: 5,
  },
  {
    id: "actions",
    label: "Action Items",
    icon: "CheckSquare",
    matchKeys: ["action"],
    kind: "content",
    order: 6,
  },
]
