import type { ModuleManifest } from "@/features/modules/types"
import { reviewChrome, TRADING_SECTIONS } from "@/features/modules/manifests/reviewSections"

export const tradingManifest: ModuleManifest = {
  id: "trading",
  name: "Trading",
  shortName: "Trading",
  tagline: "Professional trading journal",
  parserType: "trading",
  destinationModule: "trading",
  ready: true,
  route: "/trading",
  identity: { icon: "CandlestickChart", mood: "terminal" },
  theme: {
    mode: "dark",
    tokens: {
      bg: "transparent",
      fg: "hsl(40 10% 96%)",
      muted: "hsl(220 8% 62%)",
      card: "rgba(8, 12, 18, 0.72)",
      border: "rgba(52, 211, 153, 0.14)",
      accent: "#22c55e",
      accentSoft: "rgba(34, 197, 94, 0.14)",
      positive: "hsl(152 64% 48%)",
      negative: "hsl(0 72% 58%)",
      warning: "hsl(38 92% 55%)",
      paper: "rgba(6, 10, 16, 0.5)",
      glow: "rgba(16, 185, 129, 0.14)",
      progress: "rgba(52, 211, 153, 0.75)",
      radius: "1.25rem",
    },
    fontMono: "ui-monospace, SFMono-Regular, Menlo, monospace",
  },
  import: {
    upload: {
      eyebrow: "Trading · Import",
      title: "Trading Notebook",
      description: "Upload session pages — date, market, and trades will be structured for your journal.",
      dropTitle: "Drop trading notebook pages",
      dropHint: "Session scans · PNG, JPG, HEIC",
      sessionLabel: "Session / notebook title",
      sessionPlaceholder: "e.g. NIFTY Monday open",
      addImagesLabel: "Add pages",
      changeImagesLabel: "Change pages",
      processLabel: "Process session",
      reprocessLabel: "Re-process session",
    },
    understand: {
      title: "Trading document?",
      description: "Confirm Trading to review market context, setups, and trades.",
    },
    review: reviewChrome({
      title: "Review Trading Day",
      description: "Market context, observation, setups, execution, psychology, and lessons.",
      draftHeading: "Trading draft",
      imagesHeading: "Original Pages",
      saveLabel: "Save Journal",
      successTitle: "Successfully Saved!",
      successCta: "View in Trading",
      successRoute: "/trading?tab=days",
    }),
    motion: ["tick-flash", "fade-rise"],
  },
  review: {
    layout: "split-terminal",
    hero: "notebook",
    showConfidence: true,
    fieldGroups: [
      { id: "header", label: "Session", icon: "Calendar", order: 0 },
      { id: "main", label: "Market Context", icon: "LineChart", order: 1 },
      { id: "body", label: "Day sections", icon: "Notebook", order: 2 },
      { id: "trades", label: "Trades", icon: "CandlestickChart", order: 3 },
    ],
    sections: TRADING_SECTIONS,
  },
  surfaces: {
    headerStyle: "terminal",
    navStyle: "dense",
    dashboardWidgets: ["timeline", "day-insights", "open-import"],
  },
}
